### ISSUE TITLE
iOS Party, 16 июля

### ISSUE THREAD

**Issue by leominov** [leominov/it-events-ekb#187]
[iOS Party](https://events.yandex.ru/events/meetings/09-july-2019/)

> Недавно прошла WWDC 2019. После вступительной презентации мир немного поменялся: новый фреймворк SwiftUI обещает перевернуть создание интерфейсов во всей экосистеме. Обсудим все изменения и наметим ландшафт iOS-разработки на ближайший год. Об анонсах и атмосфере WWDC можно будет узнать из первых рук: от руководителя службы Яндекс.Карт и Яндекс.Метро Юрия Подорожного, который был на конференции, и от других спикеров.

**Где**: Хохрякова,10, БЦ «Палладиум»
**Когда**: 16 июля, 18:30
**Регистрация**: https://events.yandex.ru/events/meetings/09-july-2019/register/
**Взять с собой**: –

**Comment by zummenix** [comment]
Интересно что, в прямой ссылке указано `09-july-2019`, а в остальных местах дата `16 ИЮЛЯ, 18:30`. Скорее всего, правильней второе )

**Comment by leominov** [comment]
Точно, перенесли :)
