### ISSUE TITLE
UralGameNight #1, 14 июля

### ISSUE THREAD

**Issue by FarSeeing** [leominov/it-events-ekb#194]
[UralGameNight #1](https://ugj.timepad.ru/event/1004777/)
https://vk.com/feed?w=wall-182899224_3

UralGameNight — это мероприятие для разработчиков игр и всех причастных к игровой индустрии. Мы проводим ежемесячные встречи, на которых можно познакомиться с коллегами из индустрии, завести приятные и полезные связи и контакты.

**Где**: ProRockBar по адресу улица 8 Марта, 13, Екатеринбург
**Когда**: воскресение 14-го июля в 20:00 
**Регистрация**: 
Количество участников ограничено вместимостью бара. Это ровно 30 человек.
Поэтому регистрация обязательна.
Важно, если ты не уверен на 100%, что пойдешь – не регистрируйся. Пусть твое место займет тот, кто точно придет.
Регаться тут: https://ugj.timepad.ru/event/1004777/

**Comment by leominov** [comment]
👍
