### ISSUE TITLE
Big Monitoring Meetup #2, 17 мая

### ISSUE THREAD

**Issue by leominov** [leominov/it-events-ekb#56]
[Big Monitoring Meetup #2](https://eventuer.timepad.ru/event/702213/)

> Приглашаем технических специалистов, управляющих и владельцев бизнеса на BMM#2!

**Где**: [online](https://www.youtube.com/channel/UCyQ9sLBi9F3Mo_LRQrJ6RNg)
**Когда**: 17 мая, 11:00
**Регистрация**: https://eventuer.timepad.ru/event/702213/
**Взять с собой**: –

**Comment by evilj0e** [comment]
Это же будет в Спб. Трансляция?

**Comment by leominov** [comment]
Ага, трансляция
